name: CI

on: [push]

jobs:
  test:
    name: Test Stable Diffusion
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install Cog
        run: curl -o /usr/local/bin/cog -L "https://github.com/replicate/cog/releases/latest/download/cog_$(uname -s)_$(uname -m)" && chmod +x /usr/local/bin/cog
      - name: Cog login
        run: echo "8b0cc99692a5312526fbc6a1d40456750dbd39a1" | cog login --token-stdin
      - name: Download weights
        run: pip install -r scripts/requirements.txt
      - name: Setup weights
        run: setup python3 download.py
      - name: Push to CI model on Replicate
        run: cog push r8.im/moezilla/artjourney-anime
